version: '3'

services:
  php-env:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  mysql_db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      # MYSQL_DATABASE: your_database
      # MYSQL_USER: your_username
      # MYSQL_PASSWORD: your_password

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      # PMA_HOST: db
      # MYSQL_ROOT_PASSWORD: root_password
